publishDir: "../docs"

title: "tlake.io"
copyright: Tanner Lake
baseURL: "http://tlake.io"
languageCode: "en-us"
timeZone: America/Los_Angeles
enableRobotsTXT: true

enableGitInfo: true
enableEmoji: true

theme: "ananke"
defaultContentLanguage: "en"
sectionPagesMenu: "main"
paginate: 6
summaryLength: 30
disqusShortname: "tlake-io"

menu:
  dnd:
    - identifier: posts
      name: posts
      title: posts
      url: /dnd/posts
      weight: 1
    - identifier: characters
      name: characters
      title: characters
      url: /dnd/characters
      weight: 2
    - identifier: npcs
      name: npcs
      title: npcs
      url: /dnd/npcs
      weight: 3
    - identifier: locations
      name: locations
      title: locations
      url: /dnd/locations
      weight: 4
    - identifier: notes
      name: notes
      title: notes
      url: /dnd/notes
      weight: 5
    - identifier: archive
      name: archive
      title: archive
      url: /dnd/archive
      weight: 6

cascade:
  - _target:
      path: /dnd/_index.md
    family: dnd-landing
  - _target:
      path: /dnd/archive/**
    family: dnd-archive
  - _target:
      path: /dnd/characters/**
    family: dnd-character
  - _target:
      path: /dnd/locations/**
    family: dnd-location
  - _target:
      path: /dnd/notes/**
    family: dnd-note
  - _target:
      path: /dnd/npcs/**
    family: dnd-npc
  - _target:
      path: /dnd/posts/**
    family: dnd-post

taxonomies:
  character: dnd/ref/characters
  location: dnd/ref/locations
  tag: tags

params:
  mainSections:
  github: "https://github.com/tlake"
  gitlab: "https://gitlab.com/tannerlake"
  mastodon: "https://hachyderm.io/@tlake"
  twitter: "https://twitter.com/tanotaur"
  linkedin: "https://linkedin.com/in/tannerlake"
  custom_css:
    - "css/custom.css"

  primary_bg_color_class: "bg-black-80"
  primary_font_color_class: "moon-gray"

  secondary_bg_color_class: "bg-near-black"
  secondary_font_color_class: "moon-gray"

  tertiary_bg_color_class: "bg-black"
  tertiary_font_color_class: "white"
