publishDir = "../docs"

title = "tlake.io"
baseURL = "http://tlake.io"
languageCode = "en-us"
enableGitInfo = true

theme = "ananke"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6
disqusShortname = "tlake-io"

[params]
    mainSections = []
    github = "https://github.com/tlake"
    gitlab = "https://gitlab.com/tannerlake"
    twitter = "https://twitter.com/tanotaur"
    linkedin = "https://linkedin.com/in/tannerlake"
    custom_css = ["css/custom.css"]
